version: '3'

services:
  frontend:
    hostname: frontend
    container_name: frontend-exemplo-reactapp
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development